highlighter: rouge
baseurl: /sesame23
menu_header: ESC@SESAME 2023
exercises_repo: https://github.com/infn-esc/sesame23/blob/main
menu:
  -
    name: basic
    label: BASICS
    items:
    - name: environment
      label: Environment
    - name: compiling
      label: Compiling
  - name: architecture
    label: ARCHITECTURE
    items:
    - name: discoverHW
      label: Discover Hardware Architecture
    - name: perf
      label: Profiling using "perf"
  - name: cpp
    label: C++
    items:
    - name: algorithms
      label: Algorithms
    - name: pointers
      label: Managing resources
    - name: move_ops
      label: Move operations
    - name: rvo
      label: Return Value Optimization
    - name: containers
      label: Containers
    - name: compiletime
      label: Compile-time computation
  - name: parallelism
    label: PARALLELISM
    items:
    - name: parcpp
      label: Parallel C++
    - name: cuda
      label: CUDA
    - name: mpi
      label: MPI

defaults:
  -
    scope:
      path: "basic/"
      type: "posts"
    values:
      category: "basic"
      layout: "main"
